name: Build & Release SSM
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check Version
        env:
          REF: ${{ inputs.tag }}
        run: |
          tag=${{ inputs.tag }}
          version=$(echo $tag | sed 's/v//g')
          echo "VERSION=$version" >> $GITHUB_OUTPUT
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Install libusb
        shell: bash
        run: |
          sudo apt install -y libusb-dev libusb-1.0-0-dev
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24
      - name: Build
        run: |
          go build -o ssm-${env:VERSION}-linux_amd64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssm linux ${{ inputs.tag }} amd64
          path: ./ssm-*-linux_amd64
